apiVersion: v1
kind: ConfigMap
metadata:
  name: stats-service-config
  namespace: app
data:
  APP_NAME: "stats-service"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8006"
  CORS_ORIGINS: "*"
  DATABASE_URL: "postgresql+psycopg2://postgres:postgres123@postgres.data.svc.cluster.local:5432/salarydb"