export interface SalaryEntry {
  id: string
  role: string
  company: string
  country: string
  city: string
  experienceLevel: "Junior" | "Mid" | "Senior" | "Lead" | "Principal" | "Staff"
  yearsOfExperience: number
  baseSalary: number
  currency: string
  totalCompensation: number
  bonuses: number
  stockOptions: number
  submittedAt: string
  upvotes: number
  downvotes: number
  status?: "PENDING" | "APPROVED" | "REJECTED" | "REPORTED"
  isVerified: boolean
  techStack: string[]
  employmentType: "Full-time" | "Part-time" | "Contract" | "Freelance"
  remotePolicy: "Remote" | "Hybrid" | "On-site"
}

export const COUNTRIES = [
  "Sri Lanka",
  "India",
  "United Kingdom",
  "Germany",
  "Netherlands",
  "Singapore",
  "United States",
  "Canada",
  "Australia",
  "United Arab Emirates",
  "Sweden",
  "Ireland",
  "France",
  "Japan",
  "Switzerland",
]

export const ROLES = [
  "Software Engineer",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "DevOps Engineer",
  "Data Scientist",
  "Data Engineer",
  "Product Manager",
  "UX Designer",
  "QA Engineer",
  "Mobile Developer",
  "Machine Learning Engineer",
  "Cloud Architect",
  "Engineering Manager",
  "Security Engineer",
  "Site Reliability Engineer",
]

export const COMPANIES = [
  "Google",
  "Microsoft",
  "Amazon",
  "Meta",
  "Apple",
  "Netflix",
  "Spotify",
  "Shopify",
  "Stripe",
  "Atlassian",
  "WSO2",
  "Sysco LABS",
  "IFS",
  "Virtusa",
  "99x",
  "Calcey",
  "Enactor",
  "Zone24x7",
  "Pearson",
  "SAP",
  "Siemens",
  "Accenture",
  "Deloitte",
  "Infosys",
  "TCS",
]

export const EXPERIENCE_LEVELS = [
  "Junior",
  "Mid",
  "Senior",
  "Lead",
  "Principal",
  "Staff",
] as const

export const CURRENCIES = [
  { code: "USD", symbol: "$" },
  { code: "EUR", symbol: "E" },
  { code: "GBP", symbol: "P" },
  { code: "LKR", symbol: "Rs" },
  { code: "INR", symbol: "R" },
  { code: "SGD", symbol: "S$" },
  { code: "AUD", symbol: "A$" },
  { code: "CAD", symbol: "C$" },
  { code: "AED", symbol: "AED" },
  { code: "SEK", symbol: "kr" },
  { code: "CHF", symbol: "CHF" },
  { code: "JPY", symbol: "JPY" },
]

export const VERIFICATION_THRESHOLD = 10

const mockSalaries: SalaryEntry[] = [
  {
    id: "1",
    role: "Software Engineer",
    company: "Google",
    country: "United States",
    city: "Mountain View",
    experienceLevel: "Senior",
    yearsOfExperience: 7,
    baseSalary: 185000,
    currency: "USD",
    totalCompensation: 350000,
    bonuses: 30000,
    stockOptions: 135000,
    submittedAt: "2025-12-15",
    upvotes: 24,
    downvotes: 2,
    isVerified: true,
    techStack: ["Go", "Python", "Kubernetes"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "2",
    role: "Frontend Developer",
    company: "Sysco LABS",
    country: "Sri Lanka",
    city: "Colombo",
    experienceLevel: "Mid",
    yearsOfExperience: 3,
    baseSalary: 1200000,
    currency: "LKR",
    totalCompensation: 1500000,
    bonuses: 200000,
    stockOptions: 100000,
    submittedAt: "2026-01-05",
    upvotes: 18,
    downvotes: 1,
    isVerified: true,
    techStack: ["React", "TypeScript", "Node.js"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "3",
    role: "DevOps Engineer",
    company: "Amazon",
    country: "United Kingdom",
    city: "London",
    experienceLevel: "Senior",
    yearsOfExperience: 6,
    baseSalary: 95000,
    currency: "GBP",
    totalCompensation: 140000,
    bonuses: 15000,
    stockOptions: 30000,
    submittedAt: "2026-01-10",
    upvotes: 15,
    downvotes: 3,
    isVerified: true,
    techStack: ["AWS", "Terraform", "Docker"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "4",
    role: "Data Scientist",
    company: "Meta",
    country: "Germany",
    city: "Berlin",
    experienceLevel: "Mid",
    yearsOfExperience: 4,
    baseSalary: 85000,
    currency: "EUR",
    totalCompensation: 120000,
    bonuses: 15000,
    stockOptions: 20000,
    submittedAt: "2026-01-08",
    upvotes: 12,
    downvotes: 2,
    isVerified: true,
    techStack: ["Python", "TensorFlow", "SQL"],
    employmentType: "Full-time",
    remotePolicy: "Remote",
  },
  {
    id: "5",
    role: "Full Stack Developer",
    company: "WSO2",
    country: "Sri Lanka",
    city: "Colombo",
    experienceLevel: "Junior",
    yearsOfExperience: 1,
    baseSalary: 600000,
    currency: "LKR",
    totalCompensation: 720000,
    bonuses: 80000,
    stockOptions: 40000,
    submittedAt: "2026-01-12",
    upvotes: 8,
    downvotes: 1,
    isVerified: false,
    techStack: ["Java", "React", "Ballerina"],
    employmentType: "Full-time",
    remotePolicy: "On-site",
  },
  {
    id: "6",
    role: "Backend Developer",
    company: "Stripe",
    country: "Ireland",
    city: "Dublin",
    experienceLevel: "Senior",
    yearsOfExperience: 8,
    baseSalary: 110000,
    currency: "EUR",
    totalCompensation: 180000,
    bonuses: 25000,
    stockOptions: 45000,
    submittedAt: "2025-11-20",
    upvotes: 20,
    downvotes: 1,
    isVerified: true,
    techStack: ["Ruby", "Go", "PostgreSQL"],
    employmentType: "Full-time",
    remotePolicy: "Remote",
  },
  {
    id: "7",
    role: "Product Manager",
    company: "Spotify",
    country: "Sweden",
    city: "Stockholm",
    experienceLevel: "Lead",
    yearsOfExperience: 10,
    baseSalary: 95000,
    currency: "EUR",
    totalCompensation: 150000,
    bonuses: 20000,
    stockOptions: 35000,
    submittedAt: "2025-12-01",
    upvotes: 9,
    downvotes: 4,
    isVerified: false,
    techStack: ["Agile", "Jira", "Analytics"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "8",
    role: "Machine Learning Engineer",
    company: "Apple",
    country: "United States",
    city: "Cupertino",
    experienceLevel: "Senior",
    yearsOfExperience: 5,
    baseSalary: 200000,
    currency: "USD",
    totalCompensation: 400000,
    bonuses: 40000,
    stockOptions: 160000,
    submittedAt: "2025-12-20",
    upvotes: 30,
    downvotes: 2,
    isVerified: true,
    techStack: ["Python", "PyTorch", "Swift"],
    employmentType: "Full-time",
    remotePolicy: "On-site",
  },
  {
    id: "9",
    role: "Cloud Architect",
    company: "Microsoft",
    country: "Netherlands",
    city: "Amsterdam",
    experienceLevel: "Principal",
    yearsOfExperience: 12,
    baseSalary: 130000,
    currency: "EUR",
    totalCompensation: 220000,
    bonuses: 35000,
    stockOptions: 55000,
    submittedAt: "2026-01-03",
    upvotes: 16,
    downvotes: 0,
    isVerified: true,
    techStack: ["Azure", "Kubernetes", "Terraform"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "10",
    role: "Mobile Developer",
    company: "99x",
    country: "Sri Lanka",
    city: "Colombo",
    experienceLevel: "Mid",
    yearsOfExperience: 3,
    baseSalary: 900000,
    currency: "LKR",
    totalCompensation: 1100000,
    bonuses: 120000,
    stockOptions: 80000,
    submittedAt: "2026-01-15",
    upvotes: 6,
    downvotes: 2,
    isVerified: false,
    techStack: ["React Native", "TypeScript", "Firebase"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "11",
    role: "Engineering Manager",
    company: "Netflix",
    country: "United States",
    city: "Los Angeles",
    experienceLevel: "Lead",
    yearsOfExperience: 11,
    baseSalary: 250000,
    currency: "USD",
    totalCompensation: 500000,
    bonuses: 50000,
    stockOptions: 200000,
    submittedAt: "2025-11-10",
    upvotes: 28,
    downvotes: 3,
    isVerified: true,
    techStack: ["Java", "Microservices", "AWS"],
    employmentType: "Full-time",
    remotePolicy: "Remote",
  },
  {
    id: "12",
    role: "UX Designer",
    company: "Atlassian",
    country: "Australia",
    city: "Sydney",
    experienceLevel: "Mid",
    yearsOfExperience: 4,
    baseSalary: 110000,
    currency: "AUD",
    totalCompensation: 140000,
    bonuses: 15000,
    stockOptions: 15000,
    submittedAt: "2025-12-28",
    upvotes: 11,
    downvotes: 1,
    isVerified: true,
    techStack: ["Figma", "Sketch", "User Research"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "13",
    role: "Security Engineer",
    company: "Deloitte",
    country: "Singapore",
    city: "Singapore",
    experienceLevel: "Senior",
    yearsOfExperience: 6,
    baseSalary: 120000,
    currency: "SGD",
    totalCompensation: 160000,
    bonuses: 20000,
    stockOptions: 20000,
    submittedAt: "2026-01-20",
    upvotes: 7,
    downvotes: 0,
    isVerified: false,
    techStack: ["Penetration Testing", "SIEM", "Python"],
    employmentType: "Full-time",
    remotePolicy: "On-site",
  },
  {
    id: "14",
    role: "QA Engineer",
    company: "IFS",
    country: "Sri Lanka",
    city: "Colombo",
    experienceLevel: "Junior",
    yearsOfExperience: 2,
    baseSalary: 500000,
    currency: "LKR",
    totalCompensation: 600000,
    bonuses: 60000,
    stockOptions: 40000,
    submittedAt: "2026-02-01",
    upvotes: 5,
    downvotes: 1,
    isVerified: false,
    techStack: ["Selenium", "Cypress", "Java"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "15",
    role: "Data Engineer",
    company: "SAP",
    country: "Germany",
    city: "Munich",
    experienceLevel: "Senior",
    yearsOfExperience: 7,
    baseSalary: 90000,
    currency: "EUR",
    totalCompensation: 130000,
    bonuses: 15000,
    stockOptions: 25000,
    submittedAt: "2026-01-18",
    upvotes: 14,
    downvotes: 2,
    isVerified: true,
    techStack: ["Spark", "Scala", "Hadoop"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "16",
    role: "Site Reliability Engineer",
    company: "Google",
    country: "Switzerland",
    city: "Zurich",
    experienceLevel: "Staff",
    yearsOfExperience: 14,
    baseSalary: 200000,
    currency: "CHF",
    totalCompensation: 380000,
    bonuses: 50000,
    stockOptions: 130000,
    submittedAt: "2025-11-28",
    upvotes: 22,
    downvotes: 1,
    isVerified: true,
    techStack: ["Go", "Linux", "Prometheus"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "17",
    role: "Software Engineer",
    company: "Infosys",
    country: "India",
    city: "Bangalore",
    experienceLevel: "Junior",
    yearsOfExperience: 1,
    baseSalary: 800000,
    currency: "INR",
    totalCompensation: 900000,
    bonuses: 50000,
    stockOptions: 50000,
    submittedAt: "2026-02-05",
    upvotes: 4,
    downvotes: 3,
    isVerified: false,
    techStack: ["Java", "Spring Boot", "MySQL"],
    employmentType: "Full-time",
    remotePolicy: "On-site",
  },
  {
    id: "18",
    role: "Frontend Developer",
    company: "Shopify",
    country: "Canada",
    city: "Toronto",
    experienceLevel: "Mid",
    yearsOfExperience: 4,
    baseSalary: 115000,
    currency: "CAD",
    totalCompensation: 160000,
    bonuses: 15000,
    stockOptions: 30000,
    submittedAt: "2025-12-10",
    upvotes: 17,
    downvotes: 2,
    isVerified: true,
    techStack: ["React", "TypeScript", "GraphQL"],
    employmentType: "Full-time",
    remotePolicy: "Remote",
  },
  {
    id: "19",
    role: "Full Stack Developer",
    company: "Calcey",
    country: "Sri Lanka",
    city: "Colombo",
    experienceLevel: "Senior",
    yearsOfExperience: 6,
    baseSalary: 1800000,
    currency: "LKR",
    totalCompensation: 2200000,
    bonuses: 250000,
    stockOptions: 150000,
    submittedAt: "2026-01-25",
    upvotes: 13,
    downvotes: 1,
    isVerified: true,
    techStack: ["Node.js", "React", "AWS"],
    employmentType: "Full-time",
    remotePolicy: "Hybrid",
  },
  {
    id: "20",
    role: "Backend Developer",
    company: "Accenture",
    country: "United Arab Emirates",
    city: "Dubai",
    experienceLevel: "Mid",
    yearsOfExperience: 4,
    baseSalary: 35000,
    currency: "AED",
    totalCompensation: 45000,
    bonuses: 5000,
    stockOptions: 5000,
    submittedAt: "2026-02-08",
    upvotes: 3,
    downvotes: 0,
    isVerified: false,
    techStack: [".NET", "Azure", "SQL Server"],
    employmentType: "Full-time",
    remotePolicy: "On-site",
  },
]

export function getMockSalaries(): SalaryEntry[] {
  return mockSalaries
}

export function formatSalary(amount: number, currency: string): string {
  const currencyInfo = CURRENCIES.find((c) => c.code === currency)
  const symbol = currencyInfo?.symbol || currency
  if (amount >= 1000000) {
    return `${symbol} ${(amount / 1000000).toFixed(1)}M`
  }
  if (amount >= 1000) {
    return `${symbol} ${(amount / 1000).toFixed(0)}K`
  }
  return `${symbol} ${amount.toLocaleString()}`
}

export function getNetScore(entry: SalaryEntry): number {
  return entry.upvotes - entry.downvotes
}

export function isApproved(entry: SalaryEntry): boolean {
  return getNetScore(entry) >= VERIFICATION_THRESHOLD
}
